{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openapikit\/validationerror\/reason"]}],"hierarchy":{"paths":[["doc:\/\/OpenAPIKit\/documentation\/OpenAPIKit","doc:\/\/OpenAPIKit\/documentation\/OpenAPIKit\/ValidationError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["Linux"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"reason","role":"symbol","symbolKind":"property","externalID":"s:10OpenAPIKit15ValidationErrorV6reasonSSvp","roleHeading":"Instance Property","modules":[{"name":"OpenAPIKit"}]},"abstract":[{"text":"The reason for the validation failure.","type":"text"}],"identifier":{"url":"doc:\/\/OpenAPIKit\/documentation\/OpenAPIKit\/ValidationError\/reason","interfaceLanguage":"swift"},"references":{"doc://OpenAPIKit/documentation/OpenAPIKit":{"role":"collection","type":"topic","identifier":"doc:\/\/OpenAPIKit\/documentation\/OpenAPIKit","title":"OpenAPIKit","url":"\/documentation\/openapikit","abstract":[],"kind":"symbol"},"doc://OpenAPIKit/documentation/OpenAPIKit/ValidationError/reason":{"url":"\/documentation\/openapikit\/validationerror\/reason","identifier":"doc:\/\/OpenAPIKit\/documentation\/OpenAPIKit\/ValidationError\/reason","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"reason","role":"symbol","type":"topic","abstract":[{"text":"The reason for the validation failure.","type":"text"}]},"doc://OpenAPIKit/documentation/OpenAPIKit/ValidationError":{"type":"topic","role":"symbol","identifier":"doc:\/\/OpenAPIKit\/documentation\/OpenAPIKit\/ValidationError","url":"\/documentation\/openapikit\/validationerror","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationError"}],"abstract":[{"type":"text","text":"Validation errors are just a textual reason for validation failure and"},{"type":"text","text":" "},{"type":"text","text":"a coding path where the validation error occurred."}],"title":"ValidationError","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ValidationError"}]}}}